### PR TITLE
Fix ECONNRESET

### PR DESCRIPTION
**Pull request by JiriSko**
Fix invalid check of ECONNRESET error.

### CODE REVIEW

**Review by dai-shi — COMMENTED** [review]
Thanks of the fix. Is this because the socket server changed it (in some major versions in the past)?

**Comment by JiriSko** [comment]
I don't know when it changed but even [Node's docs](https://nodejs.org/api/net.html#serverlisten) uses `code` attribute and `err` object has following shape:
```
Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read'
}
```

**Review by dai-shi — APPROVED** [review]
Thanks for the confirmation. Maybe it's from the beginning. Anyway, let's merge.

**Comment by dai-shi** [comment]
https://www.npmjs.com/package/easy-livereload/v/1.4.4

**Pull request merged**
