### PR TITLE
Fix failing test (node-watch now fails when watchDir does not exist)

### PR DESCRIPTION
**Pull request by wan-hellopupil**
Should fix the failing test.

### CODE REVIEW

**Comment by dai-shi** [comment]
Thanks a lot! Let me merge this and see how CI goes.

**Comment by dai-shi** [comment]
Looks good: https://travis-ci.org/github/dai-shi/easy-livereload/builds/683415370
Thanks again!

**Comment by wan-hellopupil** [comment]
Yeah sorry about that.

I don't know if it's possible to configure Travis to show a tick mark / failing mark on github on opened PRs, but had it shown we could have fixed it before having it merged on master :laughing:

**Comment by dai-shi** [comment]
Yeah, it should be possible. I mean, it works in my other repositories. Let me see.

**Comment by dai-shi** [comment]
Migrated to travis-ci.com. It should be working from now.

**Pull request merged**
